flowchart LR
    BATA["Battery A"] --> F01A["F-01A 200A Class T"]
    BATB["Battery B"] --> F01B["F-01B 200A Class T"]
    BATC["Battery C"] --> F01C["F-01C 200A Class T"]

    F01A --> POSBUS["48V + battery-side bus"]
    F01B --> POSBUS
    F01C --> POSBUS
    POSBUS --> DISC["48V main disconnect"]
    DISC --> LYNX["Lynx Distributor"]

    BATA -. "2/0 AWG -" .-> NEGBUS["48V - battery-side bus"]
    BATB -. "2/0 AWG -" .-> NEGBUS
    BATC -. "2/0 AWG -" .-> NEGBUS
    NEGBUS --> SHUNT["SmartShunt 300A"]
    SHUNT --> LYNX

    ALT48["Secondary 48V alternator"] --> APM48["APM-48"]
    APM48 --> F04["F-04 150A MEGA"]
    F04 --> LYNX
    ALT48 -. "Dedicated 2/0 AWG return" .-> LYNX

    LYNX --> MULTI["MultiPlus-II 48/3000"]
    LYNX --> MPPT["SmartSolar 150/45"]
    LYNX --> ORION["Orion 48/12-30"]
